version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: ../../etc/docker/backend/Dockerfile
    # volumes:
    #   - /apps/backend:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
